# Generated by Django 5.1 on 2026-09-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='python_code',
            field=models.TextField(blank=True, help_text='Upload your raw Python code for PyScript games.', null=True),
        ),
    ]
